# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RequestHole < Formula
  desc "Request Hole is a command line tool for creating a temporary endpoint."
  homepage "https://github.com/aaronvb/request_hole"
  version "0.3.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/aaronvb/request_hole/releases/download/v0.3.0/request_hole_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "a6f889341545fd4429a18ece128e4d330c153c0fc054b3bd39d599d33512ff70"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/aaronvb/request_hole/releases/download/v0.3.0/request_hole_0.3.0_Darwin_arm64.tar.gz"
    sha256 "29b7acb7b5093086f0e0bc73fdaf1430fe907892a9ffbc55f71fc9ba24acec0d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/aaronvb/request_hole/releases/download/v0.3.0/request_hole_0.3.0_Linux_x86_64.tar.gz"
    sha256 "c40d5d00110a61c2297223f2da53cab94be15ecefe739ad50d35909271df25c7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/aaronvb/request_hole/releases/download/v0.3.0/request_hole_0.3.0_Linux_arm64.tar.gz"
    sha256 "46ded0623596cc7eb0eed7cdf86199176e5bb992ee20034d002e865eb937c4fd"
  end

  depends_on "go" => :optional

  def install
    bin.install "rh"
  end

  test do
    system "#{bin}/rh version"
  end
end
